name: CI
run-name: ${{github-actor}} is testing out GitHub Actions 😎

on:
  workflow_dispatch:
  push:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fwilhe2/setup-kotlin@main
      - run: kotlinc /kotlin/main.kt -include-runtime -d /kotlin/main.jar; java -jar /kotlin/main.jar